plugins {
    id 'groovy'
    id 'maven-publish'
    //id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version "$publishPluginVersion" // implies 'java-gradle-plugin'
    id 'org.jreleaser' version "$jreleaserPluginVersion"
}

ext {
    mavenVersion = "$mavenVersion"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation "org.apache.maven:maven-settings:$mavenVersion"
    implementation "org.apache.maven:maven-settings-builder:$mavenVersion"
    implementation "org.apache.maven:maven-model-builder:$mavenVersion"
    implementation "org.apache.maven:maven-model:$mavenVersion"
    implementation "org.apache.maven:maven-core:$mavenVersion"
    implementation "org.codehaus.plexus:plexus-cipher:$plexusVersion"
    implementation "org.codehaus.plexus:plexus-sec-dispatcher:$plexusVersion"

    testImplementation "org.assertj:assertj-core:$assertjVersion"
    // JUnit 5 BOM pom to manage JUnit 5 dependencies versions in one place
    testImplementation platform("org.junit:junit-bom:$junitVersion")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    // required for functional tests with GradleRunner:
    testImplementation gradleTestKit()
    // required for JUnit5, do not specify a version here:
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test).configureEach {
    // Using JUnit5 Platform for running tests
    useJUnitPlatform()
}

// Compile compatibility with Java 8 for both Java and Groovy sources
// to ensure that the plugin can be used in Gradle builds running on Java 8
tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Xlint:-options'
    options.release = "${project.targetCompatibility}".toInteger()
}

tasks.withType(GroovyCompile).configureEach {
    options.compilerArgs << '-Xlint:-options'
    sourceCompatibility = JavaVersion.toVersion("${project.sourceCompatibility}".toInteger())
    targetCompatibility = JavaVersion.toVersion("${project.targetCompatibility}".toInteger())
}

// Get project properties as a Map for usage in processResources task to expand properties in **/*-expanded.properties files
// to fix Gradle 9 deprecation warning about calling project in processResources during runtime
Map projectProperties = project.properties

processResources {
    filesMatching("**/*-expanded.properties") { FileCopyDetails details ->
        expand projectProperties
    }
}

// Logger var for usage within other definition scopes
Logger projectLogger = project.logger

boolean isSnapshotVersion = version.endsWith('-SNAPSHOT')
projectLogger.lifecycle('> Is {} build', isSnapshotVersion ? 'SNAPSHOT' : 'release')

// Unused variable for potential future use in conditional logic (e.g. jreleaser release configuration)
//boolean isReleaseBuild = !project.version.endsWith("-SNAPSHOT")

// Directory for staging deploy artifacts (e.g. plugin marker artifact and plugin .jar artifact)
// before being picked up by jreleaser for deployment to Maven Central
String stagingDeploySubDir = 'staging-deploy'

// Common Gradle Plugin properties for consistent usage
// within gradlePlugin and publishing configuration
String pluginDisplayName = 'Maven Settings Plugin'
String pluginDescription = """
    Gradle plugin for exposing Maven settings file configuration to Gradle Settings and projects.
    Originally forked from https://github.com/rmanibus/gradle-maven-settings-plugin.
    The plugin has been extended to be used in Settings and Project scope.
    Allows Gradle settings and build scripts to access and use the configuration defined in the user's Maven settings.xml file.
    Repositories, server credentials, mirrors and active profile properties are provided to Gradle configuration.
    The plugin supports global and user-specific Maven settings.xml files and respects Maven's rules for merging them.
    Decryption of encrypted passwords in the Maven settings.xml file is implemented making use of the Maven settings-security.xml.
    Look at the plugin's GitHub repository for usage instructions and details on enhancements of the original implementation.
""".stripIndent()
String pluginWebSiteUrlAsString = 'https://github.com/mavenplugins/gradle-maven-settings-plugin'
String pluginOrganization = 'mavenplugins'
String pluginOrganizationUrlAsString = 'https://github.com/mavenplugins'
// Note: repo URL must not end with '.git' and must not end with '/'
String pluginRepoUrlAsString = 'https://github.com/mavenplugins/gradle-maven-settings-plugin'


//Set Plugin ID as this projects Maven groupId.artifactId:
properties.ext.pluginId = "${group}.${rootProject.name}"

gradlePlugin {
    website = "${pluginWebSiteUrlAsString}"
    vcsUrl = "${pluginRepoUrlAsString}"

    plugins {
        // The plugin name - 'mavenSettings' in this case - is used to generate two publications:
        //   1. publication 'mavenSettingsPluginMarkerMaven' for the marker artifact
        //   2. publication 'pluginMaven' for the plugin .jar artifact
        // Note: Further customization of the generated publications (e.g. adding metadata to POM)
        // is done in the publishing block below.
        // It must be configured in afterEvaluate block since the publications are generated by java-gradle-plugin in an afterEvaluate callback.
        mavenSettings {
            id = "${pluginId}"
            displayName = "${pluginDisplayName}"
            description = "${pluginDescription}"
            tags = ['settings', 'maven']
            implementationClass = 'net.linguica.gradle.maven.settings.MavenSettingsPlugin'
        }
    }
}

publishing {
    // Enhance all publications with metadata for Maven Central
    // (e.g. pluginMaven, mavenSettingsPluginMarkerMaven, and any custom publications)
    // Note: afterEvaluate is necessary since java-gradle-plugin creates its publications in an afterEvaluate callback
    afterEvaluate {
        publications {
            //maven(MavenPublication) {
            // from components.java
            withType(MavenPublication) {
                // Enhance/update metadata to all publications (including mavenPlugin publication created by java-gradle-plugin)
                projectLogger.lifecycle("> Common custom configuration of publication {} ...", it.name)
                pom {
                    name = "${pluginDisplayName}"
                    description = "${pluginDescription}"
                    url = "${pluginWebSiteUrlAsString}"
                    licenses {
                        license {
                            name = 'Apache Software License, Version 2.0'
                            url = "${pluginRepoUrlAsString}/blob/master/LICENSE.txt"
                        }
                    }
                    developers {
                        developer {
                            id = "${pluginOrganization}"
                            // Let Maven Central Search show 'Public Project' as known contributors tag
                            name = 'Public Project'
                            url = "${pluginRepoUrlAsString}/graphs/contributors"
                            organization = "${pluginOrganization}"
                            organizationUrl = "${pluginOrganizationUrlAsString}/"
                        }
                    }
                    scm {
                        connection = "scm:git:${pluginRepoUrlAsString}.git"
                        developerConnection = "scm:git:${pluginRepoUrlAsString}.git"
                        url = "${pluginWebSiteUrlAsString}"
                    }
                }
            } // end of withType(MavenPublication)
            pluginMaven {
                // Customize plugin .jar related publication here
                projectLogger.lifecycle("> Custom configuration of publication {} ...", name)
                pom {
                    name = "${pluginDisplayName} (plugin jar artifact)"
                }
            }
            // <plugin name from gradlePlugin.plugins configuration>PluginMarkerMaven
            mavenSettingsPluginMarkerMaven {
                // Customize marker publication of mavenSettings here
                projectLogger.lifecycle("> Custom configuration of publication {} ...", name)
                pom {
                    //name = "${pluginDisplayName} (${((String) name).replace('PluginMarkerMaven', '')} marker artifact)"
                    name = "${pluginDisplayName}"
                }
            }
        }
    }
    repositories {
        //mavenLocal()
        maven {
            name = 'localJReleaserStaging'
            url = uri(layout.buildDirectory.dir("${stagingDeploySubDir}").get().asFile)
        }
        if (isSnapshotVersion
                && System.getenv('JRELEASER_NEXUS2_USERNAME')
                && (System.getenv('JRELEASER_NEXUS2_PASSWORD') || System.getenv('JRELEASER_NEXUS2_TOKEN'))) {
            maven {
                name = 'MavenCentralSnapshots'
                url = 'https://central.sonatype.com/repository/maven-snapshots/'
                credentials {
                    username = System.getenv('JRELEASER_NEXUS2_USERNAME') ?: 'unknown'
                    password = System.getenv('JRELEASER_NEXUS2_PASSWORD') ?: System.getenv('JRELEASER_NEXUS2_TOKEN') ?: 'unknown'
                }
            }
        }
    }
}


jreleaser {
    // Disable github release creation by jreleaser
    release {
        github {
            enabled = false
        }
    }

    // Signing required for Maven Central uploads
    // Env variables to be provided for signing:
    //   JRELEASER_GPG_PASSPHRASE: ${{ secrets.<secret_name> }}
    //   JRELEASER_GPG_SECRET_KEY: ${{ secrets.<secret_name> }}
    //   JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.<secret_name> }}
    signing {
        pgp {
            active = 'ALWAYS'
            armored = true
        }
    }

    // Env variables to be provided for Maven Central deployment:
    //   JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.<secret_name> }}
    //   JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.<secret_name> }}
    //   or JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.<secret_name> }}
    //   JRELEASER_MAVEN_CENTRAL_STAGE: 'UPLOAD', 'PUBLISH' or 'FULL'
    //     'UPLOAD' (default) - upload artifacts to staging repository but do not publish it (i.e. do not release it from staging to public)
    //     'PUBLISH' - publish staged repository (i.e. release it from staging to public) but do not upload artifacts to staging repository
    //                 (i.e. expect that artifacts are already uploaded to staging repository)
    //     'FULL' - upload artifacts to staging repository and publish it (i.e. release it from staging to public)
    //   JRELEASER_NEXUS2_USERNAME: ${{ secrets.<secret_name> }}
    //   JRELEASER_NEXUS2_PASSWORD: ${{ secrets.<secret_name> }}
    //   or JRELEASER_NEXUS2_TOKEN: ${{ secrets.<secret_name> }}
    deploy {
        maven {
            mavenCentral {
                'release-deploy' {
                    active = 'RELEASE'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    applyMavenCentralRules = true
                    // Time to wait between state transition checks, in seconds. Defaults to `20`.
                    retryDelay = 23
                    // Maximum number of attempts to verify state transition. Defaults to `100`.
                    maxRetries = 123
                    stagingRepository(layout.buildDirectory.dir("${stagingDeploySubDir}").get().asFile.path)
                }
            }
            // !!! Snapshots are to be deployed by Gradle maven-publish plugin!
            // !!! JReleaser nexus2 does not take care of merging content of an existing groupId:artifactId:maven-metadata.xml!
            //nexus2 {
            //    'snapshot-deploy' {
            //        active = 'SNAPSHOT'
            //        snapshotUrl = 'https://central.sonatype.com/repository/maven-snapshots/'
            //        applyMavenCentralRules = true
            //        snapshotSupported = true
            //        closeRepository = true
            //        releaseRepository = true
            //        stagingRepository(layout.buildDirectory.dir("${stagingDeploySubDir}").get().asFile.path)
            //    }
            //}
        }
    }
}